services:
  db:
    image: postgres:15-alpine
    container_name: business_mvp_db
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: business_mvp_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

volumes:
  postgres_data: