"""add team model and link to user

Revision ID: dcc43a32e193
Revises: 207c66ce67c7
Create Date: 2026-03-25 10:43:52.497269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc43a32e193'
down_revision: Union[str, Sequence[str], None] = '207c66ce67c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_team_join_code'), ['join_code'])
        batch_op.create_unique_constraint(batch_op.f('uq_team_name'), ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_user_team_id_team'), 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_team_id_team'), type_='foreignkey')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_team_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_team_join_code'), type_='unique')

    # ### end Alembic commands ###
